In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/singhrau0/Big-Data-Preprocessing/main/Leads.csv",na_values="Select")

In [3]:
df

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,NaN,NaN,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,NaN,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,NaN,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [4]:
df.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
How did you hear about X Education               7250
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     6855
City                                             3669
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [5]:
pd.set_option("display.max_columns",None)

In [6]:
df.columns

Index(['Prospect ID', 'Lead Number', 'Lead Origin', 'Lead Source',
       'Do Not Email', 'Do Not Call', 'Converted', 'TotalVisits',
       'Total Time Spent on Website', 'Page Views Per Visit', 'Last Activity',
       'Country', 'Specialization', 'How did you hear about X Education',
       'What is your current occupation',
       'What matters most to you in choosing a course', 'Search', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses', 'Tags', 'Lead Quality',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score',
       'I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity'],
      dtype='object')

In [7]:
df.dtypes

Prospect ID                                       object
Lead Number                                        int64
Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
How did you hear about X Education                object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                                          object
Newspaper Article                                 object
X Education Forums                                object
Newspaper                                         object
Digital Advertisement                             object
Through Recommendations                           object
Receive More Updates About Our Courses            object
Tags                                              object
Lead Quality                                      object
Update me on Supply Chain Content                 object
Get updates on DM Content                         object
Lead Profile                                      object
City                                              object
Asymmetrique Activity Index                       object
Asymmetrique Profile Index                        object
Asymmetrique Activity Score                      float64
Asymmetrique Profile Score                       float64
I agree to pay the amount through cheque          object
A free copy of Mastering The Interview            object
Last Notable Activity                             object
dtype: object

In [8]:
df.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
How did you hear about X Education               7250
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     6855
City                                             3669
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [9]:
y = pd.DataFrame((df.isnull().sum()/len(df) * 100)).reset_index()
y.columns=["Column","Percent"]
k=y[y["Percent"]>40]["Column"].to_list()
k

['How did you hear about X Education',
 'Lead Quality',
 'Lead Profile',
 'Asymmetrique Activity Index',
 'Asymmetrique Profile Index',
 'Asymmetrique Activity Score',
 'Asymmetrique Profile Score']

In [10]:
df.drop(k,axis=1,inplace=True)

In [11]:
df.isnull().sum()

Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
City                                             3669
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [12]:
df.drop(columns=["Prospect ID","Lead Number"],inplace=True)

In [13]:
df.dtypes

Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                                          object
Newspaper Article                                 object
X Education Forums                                object
Newspaper                                         object
Digital Advertisement                             object
Through Recommendations                           object
Receive More Updates About Our Courses            object
Tags                                              object
Update me on Supply Chain Content                 object
Get updates on DM Content                         object
City                                              object
I agree to pay the amount through cheque          object
A free copy of Mastering The Interview            object
Last Notable Activity                             object
dtype: object

In [14]:
#Do Not Email
#Do Not Call
#Search
#Magazine
#Newspaper Article
#X Education Forums
#Newspaper
#Digital Advertisemen
#Through Recommendations
#Receive More Updates About Our Courses
#Update me on Supply Chain Content
#Get updates on DM Content
#I agree to pay the amount through cheque
#A free copy of Mastering The Interview

##Droping these columns because of biased data where it contains more no compared to yes

In [15]:
print(df["Do Not Email"].value_counts())
print(df["Do Not Call"].value_counts())
print(df["Search"].value_counts())
print(df["Magazine"].value_counts())
print(df["Newspaper Article"].value_counts())
print(df["X Education Forums"].value_counts())
print(df["Newspaper"].value_counts())
print(df["Digital Advertisement"].value_counts())
print(df["Through Recommendations"].value_counts())
print(df["Receive More Updates About Our Courses"].value_counts())
print(df["Update me on Supply Chain Content"].value_counts())
print(df["Get updates on DM Content"].value_counts())
print(df["Through Recommendations"].value_counts())
print(df["I agree to pay the amount through cheque"].value_counts())
print(df["A free copy of Mastering The Interview"].value_counts())

Do Not Email
No     8506
Yes     734
Name: count, dtype: int64
Do Not Call
No     9238
Yes       2
Name: count, dtype: int64
Search
No     9226
Yes      14
Name: count, dtype: int64
Magazine
No    9240
Name: count, dtype: int64
Newspaper Article
No     9238
Yes       2
Name: count, dtype: int64
X Education Forums
No     9239
Yes       1
Name: count, dtype: int64
Newspaper
No     9239
Yes       1
Name: count, dtype: int64
Digital Advertisement
No     9236
Yes       4
Name: count, dtype: int64
Through Recommendations
No     9233
Yes       7
Name: count, dtype: int64
Receive More Updates About Our Courses
No    9240
Name: count, dtype: int64
Update me on Supply Chain Content
No    9240
Name: count, dtype: int64
Get updates on DM Content
No    9240
Name: count, dtype: int64
Through Recommendations
No     9233
Yes       7
Name: count, dtype: int64
I agree to pay the amount through cheque
No    9240
Name: count, dtype: int64
A free copy of Mastering The Interview
No     6352
Yes    2888
Name: count, dtype: int64

In [16]:
df.drop(columns=["Do Not Email","Do Not Call","Search","Magazine","Newspaper Article","X Education Forums","Newspaper","Digital Advertisement","Through Recommendations","Receive More Updates About Our Courses","Update me on Supply Chain Content","Get updates on DM Content","I agree to pay the amount through cheque","A free copy of Mastering The Interview"],inplace=True)

In [17]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                        36
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [18]:
obj = df.select_dtypes(include='object')
for j in obj:
    print(df[j].value_counts())

Lead Origin
Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: count, dtype: int64
Lead Source
Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: count, dtype: int64
Last Activity
Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: count, dtype: int64
Country
India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Hong Kong                  7
Bahrain                    7
Oman                       6
France                     6
unknown                    5
South Africa               4
Nigeria                    4
Germany                    4
Kuwait                     4
Canada                     4
Sweden                     3
China                      2
Asia/Pacific Region        2
Uganda                     2
Bangladesh                 2
Italy                      2
Belgium                    2
Netherlands                2
Ghana                      2
Philippines                2
Russia                     1
Switzerland                1
Vietnam                    1
Denmark                    1
Tanzania                   1
Liberia                    1
Malaysia                   1
Kenya                      1
Sri Lanka                  1
Indonesia                  1
Name: count, dtype: int64
Specialization
Finance Management                   976
Human Resource Management            848
Marketing Management                 838
Operations Management                503
Business Administration              403
IT Projects Management               366
Supply Chain Management              349
Banking, Investment And Insurance    338
Travel and Tourism                   203
Media and Advertising                203
International Business               178
Healthcare Management                159
Hospitality Management               114
E-COMMERCE                           112
Retail Management                    100
Rural and Agribusiness                73
E-Business                            57
Services Excellence                   40
Name: count, dtype: int64
What is your current occupation
Unemployed              5600
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: count, dtype: int64
What matters most to you in choosing a course
Better Career Prospects      6528
Flexibility & Convenience       2
Other                           1
Name: count, dtype: int64
Tags
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: count, dtype: int64
City
Mumbai                         3222
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: count, dtype: int64
Last Notable Activity
Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: count, dtype: int64

In [19]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                        36
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [20]:
#Checking Lead source Feature or Column Values
df["Lead Source"].isnull().sum()

36

In [21]:
df["Lead Source"].unique()

array(['Olark Chat', 'Organic Search', 'Direct Traffic', 'Google',
       'Referral Sites', 'Welingak Website', 'Reference', 'google',
       'Facebook', nan, 'blog', 'Pay per Click Ads', 'bing',
       'Social Media', 'WeLearn', 'Click2call', 'Live Chat',
       'welearnblog_Home', 'youtubechannel', 'testone', 'Press_Release',
       'NC_EDM'], dtype=object)

In [22]:
df["Lead Source"].nunique()

21

In [23]:
df["Lead Source"].value_counts()

Lead Source
Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: count, dtype: int64

In [24]:
#Based on the above checkings the lead source feature is an categorical data so we are going to fill the nan values with the mean
df["Lead Source"].mode()

0    Google
Name: Lead Source, dtype: object

In [25]:
df["Lead Source"].fillna("Google",inplace=True)

In [26]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [27]:
##Checking TotalVisits  Feature or Column Values
df["TotalVisits"].isnull().sum()

137

In [28]:
df["TotalVisits"].unique()

array([  0.,   5.,   2.,   1.,   4.,   8.,  11.,   6.,   3.,   7.,  13.,
        17.,  nan,   9.,  12.,  10.,  16.,  14.,  21.,  15.,  22.,  19.,
        18.,  20.,  43.,  30.,  23.,  55., 141.,  25.,  27.,  29.,  24.,
        28.,  26.,  74.,  41.,  54., 115., 251.,  32.,  42.])

In [29]:
df["TotalVisits"].nunique()

41

In [30]:
df["TotalVisits"].value_counts()

TotalVisits
0.0      2189
2.0      1680
3.0      1306
4.0      1120
5.0       783
6.0       466
1.0       395
7.0       309
8.0       224
9.0       164
10.0      114
11.0       86
13.0       48
12.0       45
14.0       36
16.0       21
15.0       18
17.0       16
18.0       15
20.0       12
19.0        9
21.0        6
23.0        6
24.0        5
25.0        5
27.0        5
22.0        3
29.0        2
28.0        2
26.0        2
141.0       1
55.0        1
30.0        1
43.0        1
74.0        1
41.0        1
54.0        1
115.0       1
251.0       1
32.0        1
42.0        1
Name: count, dtype: int64

In [31]:
df["TotalVisits"].value_counts()/len(df)*100

TotalVisits
0.0      23.690476
2.0      18.181818
3.0      14.134199
4.0      12.121212
5.0       8.474026
6.0       5.043290
1.0       4.274892
7.0       3.344156
8.0       2.424242
9.0       1.774892
10.0      1.233766
11.0      0.930736
13.0      0.519481
12.0      0.487013
14.0      0.389610
16.0      0.227273
15.0      0.194805
17.0      0.173160
18.0      0.162338
20.0      0.129870
19.0      0.097403
21.0      0.064935
23.0      0.064935
24.0      0.054113
25.0      0.054113
27.0      0.054113
22.0      0.032468
29.0      0.021645
28.0      0.021645
26.0      0.021645
141.0     0.010823
55.0      0.010823
30.0      0.010823
43.0      0.010823
74.0      0.010823
41.0      0.010823
54.0      0.010823
115.0     0.010823
251.0     0.010823
32.0      0.010823
42.0      0.010823
Name: count, dtype: float64

In [32]:
#Based on the above checkings the Total visits feature is an categorical data so we are going to fill the nan values with the mean
df["TotalVisits"].mode()

0    0.0
Name: TotalVisits, dtype: float64

In [33]:
df["TotalVisits"].fillna(0.0,inplace=True)

In [34]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                         0
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [35]:
##Checking Page Views Per Visit  Feature or Column Values
df["Page Views Per Visit"].isnull().sum()

137

In [36]:
df["Page Views Per Visit"].nunique()

114

In [37]:
df["Page Views Per Visit"].unique()

array([ 0.  ,  2.5 ,  2.  ,  1.  ,  4.  ,  8.  ,  2.67, 11.  ,  5.  ,
        6.  ,  3.  ,  1.33,  1.5 ,  3.5 ,  7.  ,  2.33, 13.  ,  8.5 ,
        5.5 ,  1.67,   nan,  4.5 ,  3.33, 16.  , 12.  ,  1.71,  1.8 ,
        6.5 ,  4.33, 14.  ,  3.4 , 10.  ,  1.25,  1.75,  2.63, 15.  ,
        2.25,  3.67,  1.43,  9.  ,  2.6 ,  4.75,  1.27,  3.25,  5.33,
        2.57,  2.17,  2.75,  2.8 ,  2.2 ,  2.86,  3.91,  1.4 ,  5.67,
        3.2 ,  1.38,  2.09,  2.4 , 55.  ,  5.25,  6.71,  3.57,  2.22,
        1.83,  3.6 ,  1.2 ,  1.57,  1.56,  5.4 ,  4.25,  1.31,  1.6 ,
        2.9 ,  1.23,  1.78,  3.83,  7.5 ,  1.14,  2.71,  1.45,  2.38,
        1.86,  2.29,  1.21, 12.33,  3.43,  2.56,  6.33,  1.64,  8.21,
        4.4 ,  3.17,  8.33,  1.48,  1.22, 24.  ,  3.75,  6.67,  1.54,
        2.13,  2.14,  2.45,  3.29,  4.17,  1.63,  3.38,  1.17, 14.5 ,
        3.8 ,  1.19,  3.82,  2.83,  1.93, 11.5 ,  2.08])

In [38]:
df["Page Views Per Visit"].value_counts()

Page Views Per Visit
0.00    2189
2.00    1795
3.00    1196
4.00     896
1.00     651
        ...
3.43       1
2.56       1
6.33       1
1.64       1
2.08       1
Name: count, Length: 114, dtype: int64

In [39]:
df["Page Views Per Visit"].value_counts()/len(df)*100

Page Views Per Visit
0.00    23.690476
2.00    19.426407
3.00    12.943723
4.00     9.696970
1.00     7.045455
          ...
3.43     0.010823
2.56     0.010823
6.33     0.010823
1.64     0.010823
2.08     0.010823
Name: count, Length: 114, dtype: float64

In [40]:
df["Page Views Per Visit"].mode()

0    0.0
Name: Page Views Per Visit, dtype: float64

In [41]:
df["Page Views Per Visit"].fillna(0.0,inplace=True)

In [42]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                         0
Total Time Spent on Website                         0
Page Views Per Visit                                0
Last Activity                                     103
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [43]:
##Checking Page Views Per Visit  Feature or Column Values
df["Last Activity"].isnull().sum()

103

In [44]:
df["Last Activity"].value_counts()

Last Activity
Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: count, dtype: int64

In [45]:
df["Last Activity"].value_counts() / len(df) * 100

Last Activity
Email Opened                    37.196970
SMS Sent                        29.707792
Olark Chat Conversation         10.530303
Page Visited on Website          6.926407
Converted to Lead                4.632035
Email Bounced                    3.528139
Email Link Clicked               2.889610
Form Submitted on Website        1.255411
Unreachable                      1.006494
Unsubscribed                     0.660173
Had a Phone Conversation         0.324675
Approached upfront               0.097403
View in browser link Clicked     0.064935
Email Received                   0.021645
Email Marked Spam                0.021645
Visited Booth in Tradeshow       0.010823
Resubscribed to emails           0.010823
Name: count, dtype: float64

In [46]:
df["Last Activity"].mode()

0    Email Opened
Name: Last Activity, dtype: object

In [47]:
df["Last Activity"].fillna("Email Opened",inplace=True)

In [48]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                         0
Total Time Spent on Website                         0
Page Views Per Visit                                0
Last Activity                                       0
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
City                                             3669
Last Notable Activity                               0
dtype: int64

In [49]:
#Lets check with the city data
df["City"].value_counts()

City
Mumbai                         3222
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: count, dtype: int64

In [50]:
df["City"].isnull().sum()

3669

In [51]:
# So here the null values are 3669 and the mode of the data will be mostly mumbai that is 3222 so when we are going to add any categorical data on this feature there is no use so it is biased so i am dropping the column
df.drop(columns=["City"],inplace=True)

In [52]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                         0
Total Time Spent on Website                         0
Page Views Per Visit                                0
Last Activity                                       0
Country                                          2461
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
Last Notable Activity                               0
dtype: int64

In [53]:
#Checking with Country Column or feature
df["Country"].unique()

array([nan, 'India', 'Russia', 'Kuwait', 'Oman', 'United Arab Emirates',
       'United States', 'Australia', 'United Kingdom', 'Bahrain', 'Ghana',
       'Singapore', 'Qatar', 'Saudi Arabia', 'Belgium', 'France',
       'Sri Lanka', 'China', 'Canada', 'Netherlands', 'Sweden', 'Nigeria',
       'Hong Kong', 'Germany', 'Asia/Pacific Region', 'Uganda', 'Kenya',
       'Italy', 'South Africa', 'Tanzania', 'unknown', 'Malaysia',
       'Liberia', 'Switzerland', 'Denmark', 'Philippines', 'Bangladesh',
       'Vietnam', 'Indonesia'], dtype=object)

In [54]:
df["Country"].value_counts()

Country
India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Hong Kong                  7
Bahrain                    7
Oman                       6
France                     6
unknown                    5
South Africa               4
Nigeria                    4
Germany                    4
Kuwait                     4
Canada                     4
Sweden                     3
China                      2
Asia/Pacific Region        2
Uganda                     2
Bangladesh                 2
Italy                      2
Belgium                    2
Netherlands                2
Ghana                      2
Philippines                2
Russia                     1
Switzerland                1
Vietnam                    1
Denmark                    1
Tanzania                   1
Liberia                    1
Malaysia                   1
Kenya                      1
Sri Lanka                  1
Indonesia                  1
Name: count, dtype: int64

In [55]:
df["Country"].isnull().sum()

2461

In [56]:
# So here if we are going to add the categorical data to country it would be biased so here i thought to drop the country column it is biased almost when we fill the data with the nan values also
df.drop(columns=["Country"],inplace=True)

In [57]:
df.isnull().sum()

Lead Origin                                         0
Lead Source                                         0
Converted                                           0
TotalVisits                                         0
Total Time Spent on Website                         0
Page Views Per Visit                                0
Last Activity                                       0
Specialization                                   3380
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Tags                                             3353
Last Notable Activity                               0
dtype: int64

In [58]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,What matters most to you in choosing a course,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,NaN,Unemployed,Better Career Prospects,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,NaN,Unemployed,Better Career Prospects,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Better Career Prospects,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Better Career Prospects,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,NaN,Unemployed,Better Career Prospects,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Better Career Prospects,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,Better Career Prospects,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,Better Career Prospects,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,NaN,NaN,NaN,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Better Career Prospects,Will revert after reading the email,Modified

In [59]:
df["What matters most to you in choosing a course"].value_counts()

What matters most to you in choosing a course
Better Career Prospects      6528
Flexibility & Convenience       2
Other                           1
Name: count, dtype: int64

In [60]:
df["What matters most to you in choosing a course"].isnull().sum()

2709

In [61]:
# so here What matters most to you in choosing a course this is also biased so we can drop this feature
df.drop(columns=["What matters most to you in choosing a course"],inplace=True)

In [62]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,NaN,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,NaN,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,NaN,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,NaN,NaN,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [63]:
df.columns

Index(['Lead Origin', 'Lead Source', 'Converted', 'TotalVisits',
       'Total Time Spent on Website', 'Page Views Per Visit', 'Last Activity',
       'Specialization', 'What is your current occupation', 'Tags',
       'Last Notable Activity'],
      dtype='object')

In [64]:
df.isnull().sum()

Lead Origin                           0
Lead Source                           0
Converted                             0
TotalVisits                           0
Total Time Spent on Website           0
Page Views Per Visit                  0
Last Activity                         0
Specialization                     3380
What is your current occupation    2690
Tags                               3353
Last Notable Activity                 0
dtype: int64

In [65]:
df["Specialization"].value_counts()

Specialization
Finance Management                   976
Human Resource Management            848
Marketing Management                 838
Operations Management                503
Business Administration              403
IT Projects Management               366
Supply Chain Management              349
Banking, Investment And Insurance    338
Travel and Tourism                   203
Media and Advertising                203
International Business               178
Healthcare Management                159
Hospitality Management               114
E-COMMERCE                           112
Retail Management                    100
Rural and Agribusiness                73
E-Business                            57
Services Excellence                   40
Name: count, dtype: int64

In [66]:
df["Specialization"].unique()

array([nan, 'Business Administration', 'Media and Advertising',
       'Supply Chain Management', 'IT Projects Management',
       'Finance Management', 'Travel and Tourism',
       'Human Resource Management', 'Marketing Management',
       'Banking, Investment And Insurance', 'International Business',
       'E-COMMERCE', 'Operations Management', 'Retail Management',
       'Services Excellence', 'Hospitality Management',
       'Rural and Agribusiness', 'Healthcare Management', 'E-Business'],
      dtype=object)

In [67]:
df["Specialization"].nunique()

18

In [68]:
df["Specialization"].isnull().sum()

3380

In [69]:
df["Specialization"].mode()

0    Finance Management
Name: Specialization, dtype: object

In [70]:
df["What is your current occupation"].value_counts()

What is your current occupation
Unemployed              5600
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: count, dtype: int64

In [71]:
df["Tags"].value_counts()

Tags
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: count, dtype: int64

In [72]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,NaN,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,NaN,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,NaN,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,NaN,NaN,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [73]:
df["What is your current occupation"].unique()

array(['Unemployed', 'Student', nan, 'Working Professional',
       'Businessman', 'Other', 'Housewife'], dtype=object)

In [74]:
df["What is your current occupation"].isnull().sum()

2690

In [75]:
df["What is your current occupation"].fillna("Unknown",inplace=True)

In [76]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,NaN,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,NaN,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,NaN,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,NaN,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [77]:
df["What is your current occupation"].value_counts()

What is your current occupation
Unemployed              5600
Unknown                 2690
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: count, dtype: int64

In [78]:
df["Tags"].value_counts()

Tags
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: count, dtype: int64

In [79]:
df["Tags"].unique()

array(['Interested in other courses', 'Ringing',
       'Will revert after reading the email', nan, 'Lost to EINS',
       'In confusion whether part time or DLP', 'Busy', 'switched off',
       'in touch with EINS', 'Already a student',
       'Diploma holder (Not Eligible)', 'Graduation in progress',
       'Closed by Horizzon', 'number not provided', 'opp hangup',
       'Not doing further education', 'invalid number',
       'wrong number given', 'Interested  in full time MBA',
       'Still Thinking', 'Lost to Others',
       'Shall take in the next coming month', 'Lateral student',
       'Interested in Next batch', 'Recognition issue (DEC approval)',
       'Want to take admission but has financial problems',
       'University not recognized'], dtype=object)

In [80]:
df["Tags"].isnull().sum()

3353

In [81]:
df["Tags"].mode()

0    Will revert after reading the email
Name: Tags, dtype: object

In [82]:
df["Tags"].fillna("Unknown",inplace=True)

In [83]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,NaN,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,NaN,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,NaN,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [84]:
df.isnull().sum()

Lead Origin                           0
Lead Source                           0
Converted                             0
TotalVisits                           0
Total Time Spent on Website           0
Page Views Per Visit                  0
Last Activity                         0
Specialization                     3380
What is your current occupation       0
Tags                                  0
Last Notable Activity                 0
dtype: int64

In [85]:
df["Specialization"].value_counts()

Specialization
Finance Management                   976
Human Resource Management            848
Marketing Management                 838
Operations Management                503
Business Administration              403
IT Projects Management               366
Supply Chain Management              349
Banking, Investment And Insurance    338
Travel and Tourism                   203
Media and Advertising                203
International Business               178
Healthcare Management                159
Hospitality Management               114
E-COMMERCE                           112
Retail Management                    100
Rural and Agribusiness                73
E-Business                            57
Services Excellence                   40
Name: count, dtype: int64

In [86]:
df["Specialization"].isnull().sum()

3380

In [87]:
df["Specialization"].unique()

array([nan, 'Business Administration', 'Media and Advertising',
       'Supply Chain Management', 'IT Projects Management',
       'Finance Management', 'Travel and Tourism',
       'Human Resource Management', 'Marketing Management',
       'Banking, Investment And Insurance', 'International Business',
       'E-COMMERCE', 'Operations Management', 'Retail Management',
       'Services Excellence', 'Hospitality Management',
       'Rural and Agribusiness', 'Healthcare Management', 'E-Business'],
      dtype=object)

In [88]:
df["Specialization"].mode()

0    Finance Management
Name: Specialization, dtype: object

In [89]:
df["Specialization"].fillna("Unknown",inplace=True)

In [90]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [91]:
df.isnull().sum()

Lead Origin                        0
Lead Source                        0
Converted                          0
TotalVisits                        0
Total Time Spent on Website        0
Page Views Per Visit               0
Last Activity                      0
Specialization                     0
What is your current occupation    0
Tags                               0
Last Notable Activity              0
dtype: int64

In [92]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [93]:
df.dtypes

Lead Origin                         object
Lead Source                         object
Converted                            int64
TotalVisits                        float64
Total Time Spent on Website          int64
Page Views Per Visit               float64
Last Activity                       object
Specialization                      object
What is your current occupation     object
Tags                                object
Last Notable Activity               object
dtype: object

In [94]:
df.drop_duplicates()

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [95]:
df.isnull().sum()

Lead Origin                        0
Lead Source                        0
Converted                          0
TotalVisits                        0
Total Time Spent on Website        0
Page Views Per Visit               0
Last Activity                      0
Specialization                     0
What is your current occupation    0
Tags                               0
Last Notable Activity              0
dtype: int64

In [96]:
df.to_csv("Cleaned_Data1.csv",index=False)

In [97]:
df

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [101]:
df[df["Specialization"]=="Unknown"]

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.0,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.5,Email Opened,Unknown,Unemployed,Ringing,Email Opened
4,Landing Page Submission,Google,1,2.0,1428,1.0,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
5,API,Olark Chat,0,0.0,0,0.0,Olark Chat Conversation,Unknown,Unknown,Unknown,Modified
7,API,Olark Chat,0,0.0,0,0.0,Olark Chat Conversation,Unknown,Unknown,Unknown,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9208,API,Google,0,2.0,181,2.0,SMS Sent,Unknown,Unknown,Unknown,Modified
9214,API,Organic Search,1,2.0,881,2.0,SMS Sent,Unknown,Unknown,Unknown,SMS Sent
9217,API,Olark Chat,0,0.0,0,0.0,SMS Sent,Unknown,Unemployed,Ringing,SMS Sent
9226,API,Olark Chat,0,0.0,0,0.0,SMS Sent,Unknown,Unemployed,Ringing,Modified
9233,API,Direct Traffic,1,13.0,1409,2.6,SMS Sent,Unknown,Unemployed,Will revert after reading the email,SMS Sent

In [102]:
df.drop_duplicates()

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [107]:
a = df.drop_duplicates()

In [108]:
a

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [110]:
a

,Lead Origin,Lead Source,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,Last Activity,Specialization,What is your current occupation,Tags,Last Notable Activity
0,API,Olark Chat,0,0.0,0,0.00,Page Visited on Website,Unknown,Unemployed,Interested in other courses,Modified
1,API,Organic Search,0,5.0,674,2.50,Email Opened,Unknown,Unemployed,Ringing,Email Opened
2,Landing Page Submission,Direct Traffic,1,2.0,1532,2.00,Email Opened,Business Administration,Student,Will revert after reading the email,Email Opened
3,Landing Page Submission,Direct Traffic,0,1.0,305,1.00,Unreachable,Media and Advertising,Unemployed,Ringing,Modified
4,Landing Page Submission,Google,1,2.0,1428,1.00,Converted to Lead,Unknown,Unemployed,Will revert after reading the email,Modified
...,...,...,...,...,...,...,...,...,...,...,...
9235,Landing Page Submission,Direct Traffic,1,8.0,1845,2.67,Email Marked Spam,IT Projects Management,Unemployed,Will revert after reading the email,Email Marked Spam
9236,Landing Page Submission,Direct Traffic,0,2.0,238,2.00,SMS Sent,Media and Advertising,Unemployed,wrong number given,SMS Sent
9237,Landing Page Submission,Direct Traffic,0,2.0,199,2.00,SMS Sent,Business Administration,Unemployed,invalid number,SMS Sent
9238,Landing Page Submission,Google,1,3.0,499,3.00,SMS Sent,Human Resource Management,Unknown,Unknown,SMS Sent
9239,Landing Page Submission,Direct Traffic,1,6.0,1279,3.00,SMS Sent,Supply Chain Management,Unemployed,Will revert after reading the email,Modified

In [112]:
a.dtypes

Lead Origin                         object
Lead Source                         object
Converted                            int64
TotalVisits                        float64
Total Time Spent on Website          int64
Page Views Per Visit               float64
Last Activity                       object
Specialization                      object
What is your current occupation     object
Tags                                object
Last Notable Activity               object
dtype: object